name: Audit Project Licenses

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  audit-node-project-licenses:
    uses: ./.github/workflows/audit_node_repo.yml
    with:
      path: ""
      repo: "jpfulton/net-sms-notifier-cli"
      repo_name: "net-sms-notifier-cli"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      personal_access_token: ${{ secrets.personal_access_token }}
