name: Audit Project Licenses

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  load-configuration:
    name: "Load JSON Configuration"
    runs-on: ubuntu-latest
    outputs:
      node-repositories: ${{ steps.node-repos-configuration.outputs.node-repositories-json }}
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Load Node Repository Configuration"
        id: node-repos-configuration
        run: |
          JSON="$(cat ./.github/configuration/node-repositories.json)";
          JSON=${JSON//$'\n'/};
          echo "node-repositories-json=$JSON" >> $GITHUB_OUTPUT;

  audit-node-project-licenses:
    name: "Audit: ${{ matrix.repository.repo_name }}"
    needs: load-configuration
    strategy:
      fail-fast: false
      matrix: 
        repository: ${{ fromJson(needs.load-configuration.outputs.node-repositories) }}
    uses: ./.github/workflows/audit_node_repo.yml
    with:
      path: ${{ matrix.repository.path }}
      repo: ${{ matrix.repository.repo }}
      repo_name: ${{ matrix.repository.repo_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      personal_access_token: ${{ secrets.personal_access_token }}
